<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\DomainPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

final class DomainPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * All prices are in USD.
     */
    public function run(): void
    {
        $tlds = [
            // --- Local (.rw) TLDs ---
            [
                'uuid' => Str::uuid(),
                'tld' => '.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.co.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.org.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.ac.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.gov.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.mil.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.net.rw',
                'type' => 'local',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 65.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],

            // --- International TLDs ---
            [
                'uuid' => Str::uuid(),
                'tld' => '.com',
                'type' => 'international',
                'register_price' => 15.00,
                'renewal_price' => 15.00,
                'transfer_price' => 15.00,
                'redemption_price' => 92.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.net',
                'type' => 'international',
                'register_price' => 17.00,
                'renewal_price' => 17.00,
                'transfer_price' => 17.00,
                'redemption_price' => 100.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.org',
                'type' => 'international',
                'register_price' => 16.00,
                'renewal_price' => 16.00,
                'transfer_price' => 16.00,
                'redemption_price' => 96.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => '.info',
                'type' => 'international',
                'register_price' => 19.00,
                'renewal_price' => 19.00,
                'transfer_price' => 19.00,
                'redemption_price' => 108.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'biz',
                'type' => 'international',
                'register_price' => 18.00,
                'renewal_price' => 18.00,
                'transfer_price' => 18.00,
                'redemption_price' => 104.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'co',
                'type' => 'international',
                'register_price' => 27.00,
                'renewal_price' => 27.00,
                'transfer_price' => 27.00,
                'redemption_price' => 138.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'io',
                'type' => 'international',
                'register_price' => 50.00,
                'renewal_price' => 50.00,
                'transfer_price' => 50.00,
                'redemption_price' => 192.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ai',
                'type' => 'international',
                'register_price' => 69.00,
                'renewal_price' => 69.00,
                'transfer_price' => 69.00,
                'redemption_price' => 231.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'dev',
                'type' => 'international',
                'register_price' => 19.00,
                'renewal_price' => 19.00,
                'transfer_price' => 19.00,
                'redemption_price' => 115.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'app',
                'type' => 'international',
                'register_price' => 22.00,
                'renewal_price' => 22.00,
                'transfer_price' => 22.00,
                'redemption_price' => 123.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'tech',
                'type' => 'international',
                'register_price' => 42.00,
                'renewal_price' => 42.00,
                'transfer_price' => 42.00,
                'redemption_price' => 154.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'software',
                'type' => 'international',
                'register_price' => 31.00,
                'renewal_price' => 31.00,
                'transfer_price' => 31.00,
                'redemption_price' => 138.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'system',
                'type' => 'international',
                'register_price' => 23.00,
                'renewal_price' => 23.00,
                'transfer_price' => 23.00,
                'redemption_price' => 131.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'cloud',
                'type' => 'international',
                'register_price' => 25.00,
                'renewal_price' => 25.00,
                'transfer_price' => 25.00,
                'redemption_price' => 135.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'digital',
                'type' => 'international',
                'register_price' => 22.00,
                'renewal_price' => 22.00,
                'transfer_price' => 22.00,
                'redemption_price' => 123.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'agency',
                'type' => 'international',
                'register_price' => 20.00,
                'renewal_price' => 20.00,
                'transfer_price' => 20.00,
                'redemption_price' => 115.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'solutions',
                'type' => 'international',
                'register_price' => 24.00,
                'renewal_price' => 24.00,
                'transfer_price' => 24.00,
                'redemption_price' => 127.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'enterprises',
                'type' => 'international',
                'register_price' => 26.00,
                'renewal_price' => 26.00,
                'transfer_price' => 26.00,
                'redemption_price' => 135.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'company',
                'type' => 'international',
                'register_price' => 15.00,
                'renewal_price' => 15.00,
                'transfer_price' => 15.00,
                'redemption_price' => 92.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'industries',
                'type' => 'international',
                'register_price' => 29.00,
                'renewal_price' => 29.00,
                'transfer_price' => 29.00,
                'redemption_price' => 146.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'xyz',
                'type' => 'international',
                'register_price' => 9.00,
                'renewal_price' => 9.00,
                'transfer_price' => 9.00,
                'redemption_price' => 69.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'online',
                'type' => 'international',
                'register_price' => 14.00,
                'renewal_price' => 14.00,
                'transfer_price' => 14.00,
                'redemption_price' => 85.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'site',
                'type' => 'international',
                'register_price' => 13.00,
                'renewal_price' => 13.00,
                'transfer_price' => 13.00,
                'redemption_price' => 81.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'website',
                'type' => 'international',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 77.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'space',
                'type' => 'international',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 73.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'icu',
                'type' => 'international',
                'register_price' => 8.00,
                'renewal_price' => 8.00,
                'transfer_price' => 8.00,
                'redemption_price' => 62.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'top',
                'type' => 'international',
                'register_price' => 7.00,
                'renewal_price' => 7.00,
                'transfer_price' => 7.00,
                'redemption_price' => 58.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'link',
                'type' => 'international',
                'register_price' => 11.00,
                'renewal_price' => 11.00,
                'transfer_price' => 11.00,
                'redemption_price' => 73.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'click',
                'type' => 'international',
                'register_price' => 10.00,
                'renewal_price' => 10.00,
                'transfer_price' => 10.00,
                'redemption_price' => 69.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'art',
                'type' => 'international',
                'register_price' => 19.00,
                'renewal_price' => 19.00,
                'transfer_price' => 19.00,
                'redemption_price' => 108.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'design',
                'type' => 'international',
                'register_price' => 35.00,
                'renewal_price' => 35.00,
                'transfer_price' => 35.00,
                'redemption_price' => 138.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'photography',
                'type' => 'international',
                'register_price' => 23.00,
                'renewal_price' => 23.00,
                'transfer_price' => 23.00,
                'redemption_price' => 123.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'studio',
                'type' => 'international',
                'register_price' => 25.00,
                'renewal_price' => 25.00,
                'transfer_price' => 25.00,
                'redemption_price' => 127.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'media',
                'type' => 'international',
                'register_price' => 29.00,
                'renewal_price' => 29.00,
                'transfer_price' => 29.00,
                'redemption_price' => 131.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'live',
                'type' => 'international',
                'register_price' => 25.00,
                'renewal_price' => 25.00,
                'transfer_price' => 25.00,
                'redemption_price' => 131.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'life',
                'type' => 'international',
                'register_price' => 23.00,
                'renewal_price' => 23.00,
                'transfer_price' => 23.00,
                'redemption_price' => 123.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'world',
                'type' => 'international',
                'register_price' => 15.00,
                'renewal_price' => 15.00,
                'transfer_price' => 15.00,
                'redemption_price' => 92.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'today',
                'type' => 'international',
                'register_price' => 18.00,
                'renewal_price' => 18.00,
                'transfer_price' => 18.00,
                'redemption_price' => 100.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'style',
                'type' => 'international',
                'register_price' => 28.00,
                'renewal_price' => 28.00,
                'transfer_price' => 28.00,
                'redemption_price' => 135.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'family',
                'type' => 'international',
                'register_price' => 22.00,
                'renewal_price' => 22.00,
                'transfer_price' => 22.00,
                'redemption_price' => 115.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'shop',
                'type' => 'international',
                'register_price' => 27.00,
                'renewal_price' => 27.00,
                'transfer_price' => 27.00,
                'redemption_price' => 131.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'store',
                'type' => 'international',
                'register_price' => 31.00,
                'renewal_price' => 31.00,
                'transfer_price' => 31.00,
                'redemption_price' => 138.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'market',
                'type' => 'international',
                'register_price' => 29.00,
                'renewal_price' => 29.00,
                'transfer_price' => 29.00,
                'redemption_price' => 135.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'sale',
                'type' => 'international',
                'register_price' => 28.00,
                'renewal_price' => 28.00,
                'transfer_price' => 28.00,
                'redemption_price' => 131.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'africa',
                'type' => 'international',
                'register_price' => 19.00,
                'renewal_price' => 19.00,
                'transfer_price' => 19.00,
                'redemption_price' => 108.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'paris',
                'type' => 'international',
                'register_price' => 35.00,
                'renewal_price' => 35.00,
                'transfer_price' => 35.00,
                'redemption_price' => 146.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'london',
                'type' => 'international',
                'register_price' => 38.00,
                'renewal_price' => 38.00,
                'transfer_price' => 38.00,
                'redemption_price' => 154.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],

            // --- Other Country Code (ccTLDs) ---
            [
                'uuid' => Str::uuid(),
                'tld' => 'ug',
                'type' => 'international',
                'register_price' => 23.00,
                'renewal_price' => 23.00,
                'transfer_price' => 23.00,
                'redemption_price' => 115.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ke',
                'type' => 'international',
                'register_price' => 23.00,
                'renewal_price' => 23.00,
                'transfer_price' => 23.00,
                'redemption_price' => 115.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'tz',
                'type' => 'international',
                'register_price' => 25.00,
                'renewal_price' => 25.00,
                'transfer_price' => 25.00,
                'redemption_price' => 119.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'za',
                'type' => 'international',
                'register_price' => 15.00,
                'renewal_price' => 15.00,
                'transfer_price' => 15.00,
                'redemption_price' => 92.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ng',
                'type' => 'international',
                'register_price' => 17.00,
                'renewal_price' => 17.00,
                'transfer_price' => 17.00,
                'redemption_price' => 100.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'us',
                'type' => 'international',
                'register_price' => 14.00,
                'renewal_price' => 14.00,
                'transfer_price' => 14.00,
                'redemption_price' => 85.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'uk',
                'type' => 'international',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 77.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ca',
                'type' => 'international',
                'register_price' => 15.00,
                'renewal_price' => 15.00,
                'transfer_price' => 15.00,
                'redemption_price' => 92.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'de',
                'type' => 'international',
                'register_price' => 12.00,
                'renewal_price' => 12.00,
                'transfer_price' => 12.00,
                'redemption_price' => 73.00,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
        ];
        DomainPrice::query()->insert($tlds);
    }
}
