<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\DomainPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

final class DomainPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * All prices are in Rwandan Francs (RWF).
     */
    public function run(): void
    {
        $tlds = [
            // --- Local (.rw) TLDs ---
            [
                'uuid' => Str::uuid(),
                'tld' => 'rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'co.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'org.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ac.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'gov.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'mil.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'net.rw',
                'type' => 'local',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 85000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],

            // --- International TLDs ---
            [
                'uuid' => Str::uuid(),
                'tld' => 'com',
                'type' => 'international',
                'register_price' => 20000,
                'renewal_price' => 20000,
                'transfer_price' => 20000,
                'redemption_price' => 120000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'net',
                'type' => 'international',
                'register_price' => 22000,
                'renewal_price' => 22000,
                'transfer_price' => 22000,
                'redemption_price' => 130000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'org',
                'type' => 'international',
                'register_price' => 21000,
                'renewal_price' => 21000,
                'transfer_price' => 21000,
                'redemption_price' => 125000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'info',
                'type' => 'international',
                'register_price' => 25000,
                'renewal_price' => 25000,
                'transfer_price' => 25000,
                'redemption_price' => 140000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'biz',
                'type' => 'international',
                'register_price' => 24000,
                'renewal_price' => 24000,
                'transfer_price' => 24000,
                'redemption_price' => 135000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'co',
                'type' => 'international',
                'register_price' => 35000,
                'renewal_price' => 35000,
                'transfer_price' => 35000,
                'redemption_price' => 180000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'io',
                'type' => 'international',
                'register_price' => 65000,
                'renewal_price' => 65000,
                'transfer_price' => 65000,
                'redemption_price' => 250000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ai',
                'type' => 'international',
                'register_price' => 90000,
                'renewal_price' => 90000,
                'transfer_price' => 90000,
                'redemption_price' => 300000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'dev',
                'type' => 'international',
                'register_price' => 25000,
                'renewal_price' => 25000,
                'transfer_price' => 25000,
                'redemption_price' => 150000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'app',
                'type' => 'international',
                'register_price' => 28000,
                'renewal_price' => 28000,
                'transfer_price' => 28000,
                'redemption_price' => 160000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'tech',
                'type' => 'international',
                'register_price' => 55000,
                'renewal_price' => 55000,
                'transfer_price' => 55000,
                'redemption_price' => 200000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'software',
                'type' => 'international',
                'register_price' => 40000,
                'renewal_price' => 40000,
                'transfer_price' => 40000,
                'redemption_price' => 180000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'system',
                'type' => 'international',
                'register_price' => 30000,
                'renewal_price' => 30000,
                'transfer_price' => 30000,
                'redemption_price' => 170000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'cloud',
                'type' => 'international',
                'register_price' => 32000,
                'renewal_price' => 32000,
                'transfer_price' => 32000,
                'redemption_price' => 175000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'digital',
                'type' => 'international',
                'register_price' => 29000,
                'renewal_price' => 29000,
                'transfer_price' => 29000,
                'redemption_price' => 160000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'agency',
                'type' => 'international',
                'register_price' => 26000,
                'renewal_price' => 26000,
                'transfer_price' => 26000,
                'redemption_price' => 150000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'solutions',
                'type' => 'international',
                'register_price' => 31000,
                'renewal_price' => 31000,
                'transfer_price' => 31000,
                'redemption_price' => 165000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'enterprises',
                'type' => 'international',
                'register_price' => 34000,
                'renewal_price' => 34000,
                'transfer_price' => 34000,
                'redemption_price' => 175000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'company',
                'type' => 'international',
                'register_price' => 20000,
                'renewal_price' => 20000,
                'transfer_price' => 20000,
                'redemption_price' => 120000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'industries',
                'type' => 'international',
                'register_price' => 38000,
                'renewal_price' => 38000,
                'transfer_price' => 38000,
                'redemption_price' => 190000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'xyz',
                'type' => 'international',
                'register_price' => 12000,
                'renewal_price' => 12000,
                'transfer_price' => 12000,
                'redemption_price' => 90000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'online',
                'type' => 'international',
                'register_price' => 18000,
                'renewal_price' => 18000,
                'transfer_price' => 18000,
                'redemption_price' => 110000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'site',
                'type' => 'international',
                'register_price' => 17000,
                'renewal_price' => 17000,
                'transfer_price' => 17000,
                'redemption_price' => 105000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'website',
                'type' => 'international',
                'register_price' => 16000,
                'renewal_price' => 16000,
                'transfer_price' => 16000,
                'redemption_price' => 100000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'space',
                'type' => 'international',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 95000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'icu',
                'type' => 'international',
                'register_price' => 10000,
                'renewal_price' => 10000,
                'transfer_price' => 10000,
                'redemption_price' => 80000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'top',
                'type' => 'international',
                'register_price' => 9000,
                'renewal_price' => 9000,
                'transfer_price' => 9000,
                'redemption_price' => 75000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'link',
                'type' => 'international',
                'register_price' => 14000,
                'renewal_price' => 14000,
                'transfer_price' => 14000,
                'redemption_price' => 95000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'click',
                'type' => 'international',
                'register_price' => 13000,
                'renewal_price' => 13000,
                'transfer_price' => 13000,
                'redemption_price' => 90000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'art',
                'type' => 'international',
                'register_price' => 25000,
                'renewal_price' => 25000,
                'transfer_price' => 25000,
                'redemption_price' => 140000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'design',
                'type' => 'international',
                'register_price' => 45000,
                'renewal_price' => 45000,
                'transfer_price' => 45000,
                'redemption_price' => 180000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'photography',
                'type' => 'international',
                'register_price' => 30000,
                'renewal_price' => 30000,
                'transfer_price' => 30000,
                'redemption_price' => 160000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'studio',
                'type' => 'international',
                'register_price' => 32000,
                'renewal_price' => 32000,
                'transfer_price' => 32000,
                'redemption_price' => 165000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'media',
                'type' => 'international',
                'register_price' => 38000,
                'renewal_price' => 38000,
                'transfer_price' => 38000,
                'redemption_price' => 170000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'live',
                'type' => 'international',
                'register_price' => 33000,
                'renewal_price' => 33000,
                'transfer_price' => 33000,
                'redemption_price' => 170000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'life',
                'type' => 'international',
                'register_price' => 30000,
                'renewal_price' => 30000,
                'transfer_price' => 30000,
                'redemption_price' => 160000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'world',
                'type' => 'international',
                'register_price' => 20000,
                'renewal_price' => 20000,
                'transfer_price' => 20000,
                'redemption_price' => 120000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'today',
                'type' => 'international',
                'register_price' => 24000,
                'renewal_price' => 24000,
                'transfer_price' => 24000,
                'redemption_price' => 130000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'style',
                'type' => 'international',
                'register_price' => 36000,
                'renewal_price' => 36000,
                'transfer_price' => 36000,
                'redemption_price' => 175000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'family',
                'type' => 'international',
                'register_price' => 28000,
                'renewal_price' => 28000,
                'transfer_price' => 28000,
                'redemption_price' => 150000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'shop',
                'type' => 'international',
                'register_price' => 35000,
                'renewal_price' => 35000,
                'transfer_price' => 35000,
                'redemption_price' => 170000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'store',
                'type' => 'international',
                'register_price' => 40000,
                'renewal_price' => 40000,
                'transfer_price' => 40000,
                'redemption_price' => 180000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'market',
                'type' => 'international',
                'register_price' => 38000,
                'renewal_price' => 38000,
                'transfer_price' => 38000,
                'redemption_price' => 175000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'sale',
                'type' => 'international',
                'register_price' => 36000,
                'renewal_price' => 36000,
                'transfer_price' => 36000,
                'redemption_price' => 170000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'africa',
                'type' => 'international',
                'register_price' => 25000,
                'renewal_price' => 25000,
                'transfer_price' => 25000,
                'redemption_price' => 140000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'paris',
                'type' => 'international',
                'register_price' => 45000,
                'renewal_price' => 45000,
                'transfer_price' => 45000,
                'redemption_price' => 190000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'london',
                'type' => 'international',
                'register_price' => 50000,
                'renewal_price' => 50000,
                'transfer_price' => 50000,
                'redemption_price' => 200000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],

            // --- Other Country Code (ccTLDs) ---
            [
                'uuid' => Str::uuid(),
                'tld' => 'ug',
                'type' => 'international',
                'register_price' => 30000,
                'renewal_price' => 30000,
                'transfer_price' => 30000,
                'redemption_price' => 150000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ke',
                'type' => 'international',
                'register_price' => 30000,
                'renewal_price' => 30000,
                'transfer_price' => 30000,
                'redemption_price' => 150000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'tz',
                'type' => 'international',
                'register_price' => 32000,
                'renewal_price' => 32000,
                'transfer_price' => 32000,
                'redemption_price' => 155000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'za',
                'type' => 'international',
                'register_price' => 20000,
                'renewal_price' => 20000,
                'transfer_price' => 20000,
                'redemption_price' => 120000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ng',
                'type' => 'international',
                'register_price' => 22000,
                'renewal_price' => 22000,
                'transfer_price' => 22000,
                'redemption_price' => 130000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'us',
                'type' => 'international',
                'register_price' => 18000,
                'renewal_price' => 18000,
                'transfer_price' => 18000,
                'redemption_price' => 110000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'uk',
                'type' => 'international',
                'register_price' => 16000,
                'renewal_price' => 16000,
                'transfer_price' => 16000,
                'redemption_price' => 100000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'ca',
                'type' => 'international',
                'register_price' => 20000,
                'renewal_price' => 20000,
                'transfer_price' => 20000,
                'redemption_price' => 120000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
            [
                'uuid' => Str::uuid(),
                'tld' => 'de',
                'type' => 'international',
                'register_price' => 15000,
                'renewal_price' => 15000,
                'transfer_price' => 15000,
                'redemption_price' => 95000,
                'min_years' => 1,
                'max_years' => 10,
                'status' => 'active',
                'description' => null,
            ],
        ];
        DomainPrice::insert($tlds);
    }
}
