<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\FeatureCategory;
use App\Models\HostingFeature;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HostingFeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $featuresCategory = FeatureCategory::where('slug', 'features')->first();
        $techSpecsCategory = FeatureCategory::where('slug', 'tech-specs')->first();
        $benefitsCategory = FeatureCategory::where('slug', 'benefits')->first();

        $features = [
            // Features Category - General Features
            [
                'uuid' => Str::uuid(),
                'name' => 'Websites',
                'slug' => 'websites',
                'description' => 'Number of websites you can host',
                'icon' => 'bi bi-globe',
                'category' => 'resources',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'websites',
                'sort_order' => 1,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'SSD Storage',
                'slug' => 'ssd-storage',
                'description' => 'Fast SSD storage space',
                'icon' => 'bi bi-hdd',
                'category' => 'resources',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'GB',
                'sort_order' => 2,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Bandwidth',
                'slug' => 'bandwidth',
                'description' => 'Monthly data transfer allowance',
                'icon' => 'bi bi-speedometer2',
                'category' => 'resources',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'unlimited',
                'unit' => 'GB',
                'sort_order' => 3,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Email Accounts',
                'slug' => 'email-accounts',
                'description' => 'Professional email accounts',
                'icon' => 'bi bi-envelope',
                'category' => 'email',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'accounts',
                'sort_order' => 4,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'MySQL Databases',
                'slug' => 'mysql-databases',
                'description' => 'MySQL database instances',
                'icon' => 'bi bi-database',
                'category' => 'resources',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'databases',
                'sort_order' => 5,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'FTP Accounts',
                'slug' => 'ftp-accounts',
                'description' => 'FTP user accounts for file management',
                'icon' => 'bi bi-folder',
                'category' => 'resources',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'accounts',
                'sort_order' => 6,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Free SSL Certificate',
                'slug' => 'free-ssl-certificate',
                'description' => 'Free SSL certificate for secure connections',
                'icon' => 'bi bi-shield-check',
                'category' => 'security',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 7,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Daily Backups',
                'slug' => 'daily-backups',
                'description' => 'Automated daily backups of your data',
                'icon' => 'bi bi-cloud-arrow-down',
                'category' => 'security',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 8,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'cPanel Control Panel',
                'slug' => 'cpanel-control-panel',
                'description' => 'Easy-to-use cPanel control panel',
                'icon' => 'bi bi-gear',
                'category' => 'features',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 9,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'One-Click WordPress Install',
                'slug' => 'one-click-wordpress-install',
                'description' => 'Install WordPress with one click',
                'icon' => 'bi bi-wordpress',
                'category' => 'features',
                'feature_category_id' => $featuresCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 10,
                'is_highlighted' => true,
            ],

            // Tech Specs Category
            [
                'uuid' => Str::uuid(),
                'name' => 'CPU Cores',
                'slug' => 'cpu-cores',
                'description' => 'Number of CPU cores allocated',
                'icon' => 'bi bi-cpu',
                'category' => 'performance',
                'feature_category_id' => $techSpecsCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'cores',
                'sort_order' => 1,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'RAM',
                'slug' => 'ram',
                'description' => 'Random Access Memory',
                'icon' => 'bi bi-memory',
                'category' => 'performance',
                'feature_category_id' => $techSpecsCategory?->id,
                'value_type' => 'numeric',
                'unit' => 'GB',
                'sort_order' => 2,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'PHP Version',
                'slug' => 'php-version',
                'description' => 'Supported PHP version',
                'icon' => 'bi bi-code-slash',
                'category' => 'performance',
                'feature_category_id' => $techSpecsCategory?->id,
                'value_type' => 'text',
                'unit' => null,
                'sort_order' => 3,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Uptime Guarantee',
                'slug' => 'uptime-guarantee',
                'description' => 'Service uptime guarantee',
                'icon' => 'bi bi-clock-history',
                'category' => 'performance',
                'feature_category_id' => $techSpecsCategory?->id,
                'value_type' => 'text',
                'unit' => '%',
                'sort_order' => 4,
                'is_highlighted' => false,
            ],

            // Benefits Category
            [
                'uuid' => Str::uuid(),
                'name' => '24/7 Support',
                'slug' => '24-7-support',
                'description' => 'Round-the-clock customer support',
                'icon' => 'bi bi-headset',
                'category' => 'support',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 1,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Money-Back Guarantee',
                'slug' => 'money-back-guarantee',
                'description' => '30-day money-back guarantee',
                'icon' => 'bi bi-arrow-counterclockwise',
                'category' => 'benefits',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'text',
                'unit' => 'days',
                'sort_order' => 2,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Free Domain',
                'slug' => 'free-domain',
                'description' => 'Free domain name included',
                'icon' => 'bi bi-link-45deg',
                'category' => 'benefits',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 3,
                'is_highlighted' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Website Builder',
                'slug' => 'website-builder',
                'description' => 'Drag-and-drop website builder included',
                'icon' => 'bi bi-tools',
                'category' => 'features',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 4,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'CDN Included',
                'slug' => 'cdn-included',
                'description' => 'Content Delivery Network for faster loading',
                'icon' => 'bi bi-cloud',
                'category' => 'performance',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 5,
                'is_highlighted' => false,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'DDoS Protection',
                'slug' => 'ddos-protection',
                'description' => 'Distributed Denial of Service protection',
                'icon' => 'bi bi-shield-lock',
                'category' => 'security',
                'feature_category_id' => $benefitsCategory?->id,
                'value_type' => 'boolean',
                'unit' => null,
                'sort_order' => 6,
                'is_highlighted' => false,
            ],
        ];

        HostingFeature::query()->insert($features);
    }
}
