<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\HostingPlanPrice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HostingPlanPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $prices = [
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 1,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],

            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 2,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 3,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 4,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 5,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 6,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 7,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 8,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 9,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 10,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 11,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 12,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 13,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 14,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 15,
                'billing_cycle' => 'monthly',
                'regular_price' => 10000,
                'renewal_price' => 10000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 1,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 2,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 3,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 4,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 5,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 6,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 7,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 8,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 9,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 10,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 11,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 12,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 13,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 14,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
            [
                'uuid' => Str::uuid(),
                'hosting_plan_id' => 15,
                'billing_cycle' => 'annually',
                'regular_price' => 100000,
                'renewal_price' => 100000,
                'promotional_price' => null,
                'discount_percentage' => null,
                'promotional_start_date' => null,
                'promotional_end_date' => null,
                'status' => 'active',
            ],
        ];

        HostingPlanPrice::query()->insert($prices);
    }
}
