<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\HostingFeature;
use App\Models\HostingPlan;
use App\Models\HostingPlanFeature;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HostingPlanFeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $planFeatures = [];

        // Get all plans by slug for an easy lookup
        $plans = HostingPlan::query()->get()->keyBy('slug');

        // Get all features by slug for easy lookup
        $features = HostingFeature::query()->get()->keyBy('slug');

        // Define feature values for each plan based on category and tier
        $planFeatureMapping = [
            // Shared Hosting Plans (category_id = 1)
            'starter' => [
                'websites' => ['value' => '1', 'is_unlimited' => false],
                'ssd-storage' => ['value' => '10', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => '5', 'is_unlimited' => false],
                'mysql-databases' => ['value' => '5', 'is_unlimited' => false],
                'ftp-accounts' => ['value' => '5', 'is_unlimited' => false],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '1', 'is_unlimited' => false],
                'ram' => ['value' => '1', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.9', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'true', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'false', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'starter-plus' => [
                'websites' => ['value' => '5', 'is_unlimited' => false],
                'ssd-storage' => ['value' => '50', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => '25', 'is_unlimited' => false],
                'mysql-databases' => ['value' => '25', 'is_unlimited' => false],
                'ftp-accounts' => ['value' => '25', 'is_unlimited' => false],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '2', 'is_unlimited' => false],
                'ram' => ['value' => '2', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.9', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'true', 'is_unlimited' => false],
                'website-builder' => ['value' => 'true', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'starter-pro' => [
                'websites' => ['value' => '10', 'is_unlimited' => false],
                'ssd-storage' => ['value' => '100', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => '50', 'is_unlimited' => false],
                'mysql-databases' => ['value' => '50', 'is_unlimited' => false],
                'ftp-accounts' => ['value' => '50', 'is_unlimited' => false],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '4', 'is_unlimited' => false],
                'ram' => ['value' => '4', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'true', 'is_unlimited' => false],
                'website-builder' => ['value' => 'true', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],

            // Reseller Hosting Plans (category_id = 2)
            'reseller-starter' => [
                'websites' => ['value' => '25', 'is_unlimited' => false],
                'ssd-storage' => ['value' => '100', 'is_unlimited' => false],
                'bandwidth' => ['value' => '500', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '2', 'is_unlimited' => false],
                'ram' => ['value' => '4', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.9', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'true', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'reseller-business' => [
                'websites' => ['value' => '50', 'is_unlimited' => false],
                'ssd-storage' => ['value' => '250', 'is_unlimited' => false],
                'bandwidth' => ['value' => '1000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '4', 'is_unlimited' => false],
                'ram' => ['value' => '8', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'true', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'reseller-gold' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '500', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '8', 'is_unlimited' => false],
                'ram' => ['value' => '16', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '30', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'true', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],

            // VPS Hosting Plans (category_id = 3)
            'vps-starter' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '40', 'is_unlimited' => false],
                'bandwidth' => ['value' => '1000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'false', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '1', 'is_unlimited' => false],
                'ram' => ['value' => '2', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.9', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'false', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'vps-business' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '100', 'is_unlimited' => false],
                'bandwidth' => ['value' => '2000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '2', 'is_unlimited' => false],
                'ram' => ['value' => '4', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'vps-gold' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '200', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '4', 'is_unlimited' => false],
                'ram' => ['value' => '8', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],

            // Dedicated Hosting Plans (category_id = 4)
            'dedicated-starter' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '500', 'is_unlimited' => false],
                'bandwidth' => ['value' => '5000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '4', 'is_unlimited' => false],
                'ram' => ['value' => '16', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '0', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'dedicated-business' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '1000', 'is_unlimited' => false],
                'bandwidth' => ['value' => '10000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '8', 'is_unlimited' => false],
                'ram' => ['value' => '32', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '0', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'dedicated-gold' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '2000', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '16', 'is_unlimited' => false],
                'ram' => ['value' => '64', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '0', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],

            // Cloud Hosting Plans (category_id = 5)
            'cloud-starter' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '50', 'is_unlimited' => false],
                'bandwidth' => ['value' => '1000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'false', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '1', 'is_unlimited' => false],
                'ram' => ['value' => '2', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'cloud-business' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '150', 'is_unlimited' => false],
                'bandwidth' => ['value' => '2000', 'is_unlimited' => false],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '4', 'is_unlimited' => false],
                'ram' => ['value' => '8', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
            'cloud-gold' => [
                'websites' => ['value' => null, 'is_unlimited' => true],
                'ssd-storage' => ['value' => '300', 'is_unlimited' => false],
                'bandwidth' => ['value' => null, 'is_unlimited' => true],
                'email-accounts' => ['value' => null, 'is_unlimited' => true],
                'mysql-databases' => ['value' => null, 'is_unlimited' => true],
                'ftp-accounts' => ['value' => null, 'is_unlimited' => true],
                'free-ssl-certificate' => ['value' => 'true', 'is_unlimited' => false],
                'daily-backups' => ['value' => 'true', 'is_unlimited' => false],
                'cpanel-control-panel' => ['value' => 'true', 'is_unlimited' => false],
                'one-click-wordpress-install' => ['value' => 'true', 'is_unlimited' => false],
                'cpu-cores' => ['value' => '8', 'is_unlimited' => false],
                'ram' => ['value' => '16', 'is_unlimited' => false],
                'php-version' => ['value' => '8.2', 'is_unlimited' => false],
                'uptime-guarantee' => ['value' => '99.99', 'is_unlimited' => false],
                '24-7-support' => ['value' => 'true', 'is_unlimited' => false],
                'money-back-guarantee' => ['value' => '7', 'is_unlimited' => false],
                'free-domain' => ['value' => 'false', 'is_unlimited' => false],
                'website-builder' => ['value' => 'false', 'is_unlimited' => false],
                'cdn-included' => ['value' => 'true', 'is_unlimited' => false],
                'ddos-protection' => ['value' => 'true', 'is_unlimited' => false],
            ],
        ];

        // Build plan features array
        foreach ($planFeatureMapping as $planSlug => $featureMap) {
            $plan = $plans->get($planSlug);

            if (! $plan) {
                continue;
            }

            $sortOrder = 0;
            foreach ($featureMap as $featureSlug => $featureData) {
                $feature = $features->get($featureSlug);

                if (! $feature) {
                    continue;
                }

                $planFeatures[] = [
                    'uuid' => Str::uuid(),
                    'hosting_plan_id' => $plan->id,
                    'hosting_feature_id' => $feature->id,
                    'feature_value' => $featureData['value'],
                    'is_unlimited' => $featureData['is_unlimited'],
                    'custom_text' => null,
                    'is_included' => true,
                    'sort_order' => $feature->sort_order ?? $sortOrder++,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        HostingPlanFeature::query()->insert($planFeatures);
    }
}
