<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

final class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            ['title' => 'user_management_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'permission_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'permission_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'permission_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'permission_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'permission_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'role_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'role_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'role_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'role_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'role_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'user_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'user_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'user_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'user_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'user_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_renew', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_transfer', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'domain_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'contact_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'contact_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'contact_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'contact_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'contact_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'setting_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'setting_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'setting_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'setting_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'setting_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'nameserver_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'nameserver_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'nameserver_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'nameserver_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'nameserver_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'profile_password_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'currency_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'currency_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'currency_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'currency_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'currency_update_rates', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'failed_registration_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'failed_registration_retry', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'failed_renewal_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'failed_renewal_retry', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'ownership_assignment_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_category_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_category_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_category_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_category_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_category_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_price_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_price_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_price_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_price_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_price_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'feature_category_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'feature_category_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'feature_category_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'feature_category_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'feature_category_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_feature_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_feature_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_feature_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_feature_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_feature_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_feature_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_feature_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_feature_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_feature_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_plan_feature_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'subscription_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'subscription_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'subscription_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'subscription_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'subscription_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_management_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_promotion_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_promotion_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_promotion_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_promotion_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'hosting_promotion_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'audit_log_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'product_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_show', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_delete', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_pricing_access', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_pricing_create', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_pricing_edit', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'tld_pricing_delete', 'created_at' => now(), 'updated_at' => now()],
        ];

        Permission::query()->upsert($permissions, ['title'], ['updated_at']);
    }
}
